services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
      - ./engines/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./engines/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file:
      - .env
    command: [ "sh", "/var/www/html/engines/command/start.sh" ]
    restart: always
    network_mode: bridge
    ports:
      - "${VARNISH_PORT:-8082}:80"
      - "${NGINX_PORT:-8081}:8081"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    network_mode: service:php
    volumes:
      - ./web:/var/www/html/web
      - ./engines/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  varnish:
    image: varnish:7.4
    container_name: varnish
    restart: always
    network_mode: service:php
    volumes:
      - ./engines/varnish/default.vcl:/etc/varnish/default.vcl
    environment:
      - VARNISH_SIZE=256M
    depends_on:
      - nginx
