services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
      - ./engines/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./engines/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file:
      - .env
    command: [ "sh", "/var/www/html/engines/command/start.sh" ]
    restart: always
    network_mode: bridge
    ports:
      - "8888:80"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./web:/var/www/html/web
      - ./engines/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always
    network_mode: service:php
